#!/usr/bin/python
#-*-coding:utf-8-*-

# Spider template.
#
# Created: #Date#
#      By: leaboy.w <leaboy.w@gmail.com>
#     Lib: Scrapy 0.12.0
#
# GNU Free Documentation License 1.3

from scrapy.item import Item, Field
from scrapy.selector import HtmlXPathSelector
from scrapy.spider import BaseSpider
from scrapy.contrib.loader import XPathItemLoader

class MyItems(Item):
    """necessary Item"""
    title = Field()
    link = Field()
    content = Field()

class MySpider(BaseSpider):
    """spider"""
    name = '#spider_name#'
    start_urls = #list_urls#
    list_xpath = '#rule_list#'

    def parse(self, response):
        hxs = HtmlXPathSelector(response)

        for x in hxs.select(self.list_xpath):
            loader = XPathItemLoader(MyItems(), selector=x)
            #xpath#

            yield loader.load_item()