# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Database.ui'
#
# Created: Thu Jul 14 15:25:42 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DatabaseDialog(object):
    def setupUi(self, DatabaseDialog):
        DatabaseDialog.setObjectName("DatabaseDialog")
        DatabaseDialog.resize(231, 147)
        self.verticalLayout = QtGui.QVBoxLayout(DatabaseDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtGui.QLabel(DatabaseDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtGui.QLabel(DatabaseDialog)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_28 = QtGui.QLabel(DatabaseDialog)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 2, 0, 1, 1)
        self.label_29 = QtGui.QLabel(DatabaseDialog)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 3, 0, 1, 1)
        self.dbhost = QtGui.QLineEdit(DatabaseDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbhost.sizePolicy().hasHeightForWidth())
        self.dbhost.setSizePolicy(sizePolicy)
        self.dbhost.setObjectName("dbhost")
        self.gridLayout.addWidget(self.dbhost, 0, 1, 1, 1)
        self.dbname = QtGui.QLineEdit(DatabaseDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbname.sizePolicy().hasHeightForWidth())
        self.dbname.setSizePolicy(sizePolicy)
        self.dbname.setObjectName("dbname")
        self.gridLayout.addWidget(self.dbname, 1, 1, 1, 1)
        self.dbuser = QtGui.QLineEdit(DatabaseDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbuser.sizePolicy().hasHeightForWidth())
        self.dbuser.setSizePolicy(sizePolicy)
        self.dbuser.setObjectName("dbuser")
        self.gridLayout.addWidget(self.dbuser, 2, 1, 1, 1)
        self.dbpw = QtGui.QLineEdit(DatabaseDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbpw.sizePolicy().hasHeightForWidth())
        self.dbpw.setSizePolicy(sizePolicy)
        self.dbpw.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.dbpw.setObjectName("dbpw")
        self.gridLayout.addWidget(self.dbpw, 3, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(DatabaseDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(DatabaseDialog)
        QtCore.QMetaObject.connectSlotsByName(DatabaseDialog)

    def retranslateUi(self, DatabaseDialog):
        DatabaseDialog.setWindowTitle(QtGui.QApplication.translate("DatabaseDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("DatabaseDialog", "数据库地址", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("DatabaseDialog", "数据库名称", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("DatabaseDialog", "数据库用户名", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("DatabaseDialog", "数据库密码", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("DatabaseDialog", "保存", None, QtGui.QApplication.UnicodeUTF8))

