# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Robot.ui'
#
# Created: Mon Aug 22 10:50:53 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_RobotDialog(object):
    def setupUi(self, RobotDialog):
        RobotDialog.setObjectName("RobotDialog")
        RobotDialog.resize(537, 462)
        self.verticalLayout = QtGui.QVBoxLayout(RobotDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(RobotDialog)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_7.setMargin(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_6 = QtGui.QGroupBox(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setStyleSheet("None")
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_6.setContentsMargins(9, 3, 6, 3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(120, 0))
        self.label_11.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.groupBox_6)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_13)
        self.robotname = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.robotname.sizePolicy().hasHeightForWidth())
        self.robotname.setSizePolicy(sizePolicy)
        self.robotname.setObjectName("robotname")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.robotname)
        self.timeout = QtGui.QSpinBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeout.sizePolicy().hasHeightForWidth())
        self.timeout.setSizePolicy(sizePolicy)
        self.timeout.setMaximum(200)
        self.timeout.setProperty("value", 3)
        self.timeout.setObjectName("timeout")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.timeout)
        self.threads = QtGui.QSpinBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threads.sizePolicy().hasHeightForWidth())
        self.threads.setSizePolicy(sizePolicy)
        self.threads.setMinimum(1)
        self.threads.setMaximum(2000)
        self.threads.setProperty("value", 100)
        self.threads.setObjectName("threads")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.threads)
        self.horizontalLayout_6.addLayout(self.formLayout_4)
        self.verticalLayout_7.addWidget(self.groupBox_6)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setStyleSheet("None")
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_8.setContentsMargins(9, 3, 6, 3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_30 = QtGui.QLabel(self.groupBox_8)
        self.label_30.setObjectName("label_30")
        self.gridLayout_6.addWidget(self.label_30, 0, 0, 3, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_31 = QtGui.QLabel(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(65, 0))
        self.label_31.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_7.addWidget(self.label_31, 0, 0, 1, 1)
        self.autourl = QtGui.QLineEdit(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autourl.sizePolicy().hasHeightForWidth())
        self.autourl.setSizePolicy(sizePolicy)
        self.autourl.setMouseTracking(True)
        self.autourl.setAcceptDrops(True)
        self.autourl.setObjectName("autourl")
        self.gridLayout_7.addWidget(self.autourl, 0, 1, 1, 2)
        self.label = QtGui.QLabel(self.groupBox_8)
        self.label.setCursor(QtCore.Qt.IBeamCursor)
        self.label.setStyleSheet("color: rgb(172, 202, 239);")
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 1, 1, 1, 2)
        self.gridLayout_6.addLayout(self.gridLayout_7, 0, 1, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox_8)
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 3, 0, 1, 1)
        self.manualurl = QtGui.QPlainTextEdit(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manualurl.sizePolicy().hasHeightForWidth())
        self.manualurl.setSizePolicy(sizePolicy)
        self.manualurl.setObjectName("manualurl")
        self.gridLayout_6.addWidget(self.manualurl, 3, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setContentsMargins(6, 3, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_46 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        self.label_46.setObjectName("label_46")
        self.gridLayout_10.addWidget(self.label_46, 0, 2, 1, 1)
        self.label_47 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setObjectName("label_47")
        self.gridLayout_10.addWidget(self.label_47, 1, 0, 1, 1)
        self.label_48 = QtGui.QLabel(self.groupBox_2)
        self.label_48.setStyleSheet("color: rgb(172, 202, 239);")
        self.label_48.setObjectName("label_48")
        self.gridLayout_10.addWidget(self.label_48, 1, 2, 1, 3)
        self.label_49 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        self.label_49.setObjectName("label_49")
        self.gridLayout_10.addWidget(self.label_49, 0, 0, 1, 1)
        self.listpagestart = QtGui.QSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listpagestart.sizePolicy().hasHeightForWidth())
        self.listpagestart.setSizePolicy(sizePolicy)
        self.listpagestart.setMaximum(999999)
        self.listpagestart.setObjectName("listpagestart")
        self.gridLayout_10.addWidget(self.listpagestart, 0, 1, 1, 1)
        self.listpageend = QtGui.QSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listpageend.sizePolicy().hasHeightForWidth())
        self.listpageend.setSizePolicy(sizePolicy)
        self.listpageend.setMaximum(999999)
        self.listpageend.setObjectName("listpageend")
        self.gridLayout_10.addWidget(self.listpageend, 0, 3, 1, 1)
        self.wildcardlen = QtGui.QSpinBox(self.groupBox_2)
        self.wildcardlen.setMaximum(9)
        self.wildcardlen.setObjectName("wildcardlen")
        self.gridLayout_10.addWidget(self.wildcardlen, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_10)
        self.gridLayout_6.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setContentsMargins(6, 3, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_50 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        self.label_50.setMinimumSize(QtCore.QSize(65, 0))
        self.label_50.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_50.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName("label_50")
        self.gridLayout_11.addWidget(self.label_50, 0, 0, 1, 1)
        self.stockdata = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stockdata.sizePolicy().hasHeightForWidth())
        self.stockdata.setSizePolicy(sizePolicy)
        self.stockdata.setMouseTracking(True)
        self.stockdata.setAcceptDrops(True)
        self.stockdata.setObjectName("stockdata")
        self.gridLayout_11.addWidget(self.stockdata, 0, 1, 1, 2)
        self.verticalLayout_4.addLayout(self.gridLayout_11)
        self.gridLayout_6.addWidget(self.groupBox_3, 2, 1, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout_6)
        self.verticalLayout_7.addWidget(self.groupBox_8)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_8.setMargin(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_9 = QtGui.QGroupBox(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setStyleSheet("None")
        self.groupBox_9.setFlat(True)
        self.groupBox_9.setCheckable(False)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_9.setContentsMargins(9, 3, 6, 3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_37 = QtGui.QLabel(self.groupBox_9)
        self.label_37.setObjectName("label_37")
        self.gridLayout_8.addWidget(self.label_37, 0, 0, 1, 1)
        self.label_38 = QtGui.QLabel(self.groupBox_9)
        self.label_38.setTextFormat(QtCore.Qt.RichText)
        self.label_38.setObjectName("label_38")
        self.gridLayout_8.addWidget(self.label_38, 1, 0, 1, 1)
        self.subjecturlrule = QtGui.QPlainTextEdit(self.groupBox_9)
        self.subjecturlrule.setObjectName("subjecturlrule")
        self.gridLayout_8.addWidget(self.subjecturlrule, 1, 1, 1, 4)
        self.label_39 = QtGui.QLabel(self.groupBox_9)
        self.label_39.setTextFormat(QtCore.Qt.RichText)
        self.label_39.setObjectName("label_39")
        self.gridLayout_8.addWidget(self.label_39, 2, 0, 1, 1)
        self.subjecturllinkrule = QtGui.QPlainTextEdit(self.groupBox_9)
        self.subjecturllinkrule.setObjectName("subjecturllinkrule")
        self.gridLayout_8.addWidget(self.subjecturllinkrule, 2, 1, 1, 4)
        self.label_40 = QtGui.QLabel(self.groupBox_9)
        self.label_40.setTextFormat(QtCore.Qt.RichText)
        self.label_40.setObjectName("label_40")
        self.gridLayout_8.addWidget(self.label_40, 3, 0, 1, 1)
        self.subjectrule = QtGui.QPlainTextEdit(self.groupBox_9)
        self.subjectrule.setObjectName("subjectrule")
        self.gridLayout_8.addWidget(self.subjectrule, 3, 1, 1, 4)
        self.label_41 = QtGui.QLabel(self.groupBox_9)
        self.label_41.setTextFormat(QtCore.Qt.RichText)
        self.label_41.setObjectName("label_41")
        self.gridLayout_8.addWidget(self.label_41, 4, 0, 1, 1)
        self.messagerule = QtGui.QPlainTextEdit(self.groupBox_9)
        self.messagerule.setObjectName("messagerule")
        self.gridLayout_8.addWidget(self.messagerule, 4, 1, 1, 4)
        self.label_43 = QtGui.QLabel(self.groupBox_9)
        self.label_43.setObjectName("label_43")
        self.gridLayout_8.addWidget(self.label_43, 5, 0, 1, 1)
        self.rule_mode_regex = QtGui.QRadioButton(self.groupBox_9)
        self.rule_mode_regex.setObjectName("rule_mode_regex")
        self.gridLayout_8.addWidget(self.rule_mode_regex, 0, 2, 1, 1)
        self.rule_mode_xpath = QtGui.QRadioButton(self.groupBox_9)
        self.rule_mode_xpath.setChecked(True)
        self.rule_mode_xpath.setObjectName("rule_mode_xpath")
        self.gridLayout_8.addWidget(self.rule_mode_xpath, 0, 1, 1, 1)
        self.reversemode = QtGui.QCheckBox(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reversemode.sizePolicy().hasHeightForWidth())
        self.reversemode.setSizePolicy(sizePolicy)
        self.reversemode.setObjectName("reversemode")
        self.gridLayout_8.addWidget(self.reversemode, 5, 1, 1, 1)
        self.linkmode = QtGui.QCheckBox(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linkmode.sizePolicy().hasHeightForWidth())
        self.linkmode.setSizePolicy(sizePolicy)
        self.linkmode.setObjectName("linkmode")
        self.gridLayout_8.addWidget(self.linkmode, 5, 2, 1, 1)
        self.downloadmode = QtGui.QCheckBox(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadmode.sizePolicy().hasHeightForWidth())
        self.downloadmode.setSizePolicy(sizePolicy)
        self.downloadmode.setObjectName("downloadmode")
        self.gridLayout_8.addWidget(self.downloadmode, 5, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 5, 4, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayout_8)
        self.verticalLayout_8.addWidget(self.groupBox_9)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.robotSave = QtGui.QPushButton(RobotDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.robotSave.sizePolicy().hasHeightForWidth())
        self.robotSave.setSizePolicy(sizePolicy)
        self.robotSave.setObjectName("robotSave")
        self.horizontalLayout_11.addWidget(self.robotSave)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_11)

        self.retranslateUi(RobotDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RobotDialog)

    def retranslateUi(self, RobotDialog):
        RobotDialog.setWindowTitle(QtGui.QApplication.translate("RobotDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("RobotDialog", "基础设置>>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("RobotDialog", "采集器名称", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("RobotDialog", "超时（秒）", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("RobotDialog", "最大线程数", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("RobotDialog", "列表页设置>>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("RobotDialog", "自动增长", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("RobotDialog", "地址:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("RobotDialog", "参数：[page]、[stock]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("RobotDialog", "手工输入", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("RobotDialog", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("RobotDialog", "到:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("RobotDialog", "通配符长度:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("RobotDialog", "说明: 长度不足时，前面补0.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("RobotDialog", "从:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("RobotDialog", "Stock", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("RobotDialog", "数据源:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("RobotDialog", "基本信息", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("RobotDialog", "采集设置>>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("RobotDialog", "匹配模式", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("RobotDialog", "列表区域识别规则<br/><font color=\'#ACCAEF\'>截取的地方加上：<br/>[list]</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("RobotDialog", "文章链接URL识别规则<br/><font color=\'#ACCAEF\'>截取的地方加上：<br/>[url]、[title]</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("RobotDialog", "文章标题识别规则<br/><font color=\'#ACCAEF\'>截取的地方加上：<br/>[title]</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("RobotDialog", "文章内容识别规则<br/><font color=\'#ACCAEF\'>截取的地方加上：<br/>[message]</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("RobotDialog", "其它设置", None, QtGui.QApplication.UnicodeUTF8))
        self.rule_mode_regex.setText(QtGui.QApplication.translate("RobotDialog", "正则", None, QtGui.QApplication.UnicodeUTF8))
        self.rule_mode_xpath.setText(QtGui.QApplication.translate("RobotDialog", "XPath", None, QtGui.QApplication.UnicodeUTF8))
        self.reversemode.setText(QtGui.QApplication.translate("RobotDialog", "倒序模式", None, QtGui.QApplication.UnicodeUTF8))
        self.linkmode.setText(QtGui.QApplication.translate("RobotDialog", "列表模式", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadmode.setText(QtGui.QApplication.translate("RobotDialog", "下载模式", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("RobotDialog", "采集规则", None, QtGui.QApplication.UnicodeUTF8))
        self.robotSave.setText(QtGui.QApplication.translate("RobotDialog", "保存", None, QtGui.QApplication.UnicodeUTF8))

