# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Robot.ui'
#
# Created: Tue Jul 19 14:18:23 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_RobotDialog(object):
    def setupUi(self, RobotDialog):
        RobotDialog.setObjectName("RobotDialog")
        RobotDialog.resize(537, 465)
        self.verticalLayout = QtGui.QVBoxLayout(RobotDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(RobotDialog)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_7.setMargin(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_6 = QtGui.QGroupBox(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setStyleSheet("None")
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_6.setContentsMargins(9, 3, 6, 3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(120, 0))
        self.label_11.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.groupBox_6)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_13)
        self.robotname = QtGui.QLineEdit(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.robotname.sizePolicy().hasHeightForWidth())
        self.robotname.setSizePolicy(sizePolicy)
        self.robotname.setObjectName("robotname")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.robotname)
        self.speed = QtGui.QSpinBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speed.sizePolicy().hasHeightForWidth())
        self.speed.setSizePolicy(sizePolicy)
        self.speed.setMaximum(99)
        self.speed.setProperty("value", 1)
        self.speed.setObjectName("speed")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.speed)
        self.threads = QtGui.QSpinBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threads.sizePolicy().hasHeightForWidth())
        self.threads.setSizePolicy(sizePolicy)
        self.threads.setMinimum(1)
        self.threads.setProperty("value", 10)
        self.threads.setObjectName("threads")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.threads)
        self.horizontalLayout_6.addLayout(self.formLayout_4)
        self.verticalLayout_7.addWidget(self.groupBox_6)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setStyleSheet("None")
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_8.setContentsMargins(9, 3, 6, 3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_30 = QtGui.QLabel(self.groupBox_8)
        self.label_30.setObjectName("label_30")
        self.gridLayout_6.addWidget(self.label_30, 0, 0, 3, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_31 = QtGui.QLabel(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(65, 0))
        self.label_31.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_7.addWidget(self.label_31, 0, 0, 1, 1)
        self.autourl = QtGui.QLineEdit(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autourl.sizePolicy().hasHeightForWidth())
        self.autourl.setSizePolicy(sizePolicy)
        self.autourl.setMouseTracking(True)
        self.autourl.setAcceptDrops(True)
        self.autourl.setObjectName("autourl")
        self.gridLayout_7.addWidget(self.autourl, 0, 1, 1, 2)
        self.label = QtGui.QLabel(self.groupBox_8)
        self.label.setCursor(QtCore.Qt.IBeamCursor)
        self.label.setStyleSheet("color: rgb(172, 202, 239);")
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 1, 1, 1, 2)
        self.gridLayout_6.addLayout(self.gridLayout_7, 0, 1, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox_8)
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 3, 0, 1, 1)
        self.manualurl = QtGui.QPlainTextEdit(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manualurl.sizePolicy().hasHeightForWidth())
        self.manualurl.setSizePolicy(sizePolicy)
        self.manualurl.setObjectName("manualurl")
        self.gridLayout_6.addWidget(self.manualurl, 3, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setContentsMargins(6, 3, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.listpagestart = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listpagestart.sizePolicy().hasHeightForWidth())
        self.listpagestart.setSizePolicy(sizePolicy)
        self.listpagestart.setMinimumSize(QtCore.QSize(45, 0))
        self.listpagestart.setMaximumSize(QtCore.QSize(45, 16777215))
        self.listpagestart.setObjectName("listpagestart")
        self.gridLayout_10.addWidget(self.listpagestart, 0, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        self.label_46.setObjectName("label_46")
        self.gridLayout_10.addWidget(self.label_46, 0, 2, 1, 1)
        self.listpageend = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listpageend.sizePolicy().hasHeightForWidth())
        self.listpageend.setSizePolicy(sizePolicy)
        self.listpageend.setMinimumSize(QtCore.QSize(45, 0))
        self.listpageend.setMaximumSize(QtCore.QSize(45, 16777215))
        self.listpageend.setObjectName("listpageend")
        self.gridLayout_10.addWidget(self.listpageend, 0, 3, 1, 1)
        self.label_47 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setObjectName("label_47")
        self.gridLayout_10.addWidget(self.label_47, 1, 0, 1, 1)
        self.wildcardlen = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wildcardlen.sizePolicy().hasHeightForWidth())
        self.wildcardlen.setSizePolicy(sizePolicy)
        self.wildcardlen.setMinimumSize(QtCore.QSize(45, 0))
        self.wildcardlen.setMaximumSize(QtCore.QSize(45, 16777215))
        self.wildcardlen.setObjectName("wildcardlen")
        self.gridLayout_10.addWidget(self.wildcardlen, 1, 1, 1, 1)
        self.label_48 = QtGui.QLabel(self.groupBox_2)
        self.label_48.setStyleSheet("color: rgb(172, 202, 239);")
        self.label_48.setObjectName("label_48")
        self.gridLayout_10.addWidget(self.label_48, 1, 2, 1, 3)
        self.label_49 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        self.label_49.setObjectName("label_49")
        self.gridLayout_10.addWidget(self.label_49, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_10)
        self.gridLayout_6.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_8)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setContentsMargins(6, 3, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_50 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        self.label_50.setMinimumSize(QtCore.QSize(65, 0))
        self.label_50.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_50.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName("label_50")
        self.gridLayout_11.addWidget(self.label_50, 0, 0, 1, 1)
        self.stockdata = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stockdata.sizePolicy().hasHeightForWidth())
        self.stockdata.setSizePolicy(sizePolicy)
        self.stockdata.setMouseTracking(True)
        self.stockdata.setAcceptDrops(True)
        self.stockdata.setObjectName("stockdata")
        self.gridLayout_11.addWidget(self.stockdata, 0, 1, 1, 2)
        self.verticalLayout_4.addLayout(self.gridLayout_11)
        self.gridLayout_6.addWidget(self.groupBox_3, 2, 1, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout_6)
        self.verticalLayout_7.addWidget(self.groupBox_8)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_8.setMargin(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_9 = QtGui.QGroupBox(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setStyleSheet("None")
        self.groupBox_9.setFlat(True)
        self.groupBox_9.setCheckable(False)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_9.setContentsMargins(9, 3, 6, 3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_37 = QtGui.QLabel(self.groupBox_9)
        self.label_37.setObjectName("label_37")
        self.gridLayout_8.addWidget(self.label_37, 0, 0, 1, 1)
        self.encode = QtGui.QLineEdit(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.encode.sizePolicy().hasHeightForWidth())
        self.encode.setSizePolicy(sizePolicy)
        self.encode.setMaximumSize(QtCore.QSize(45, 16777215))
        self.encode.setObjectName("encode")
        self.gridLayout_8.addWidget(self.encode, 0, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.groupBox_9)
        self.label_38.setTextFormat(QtCore.Qt.RichText)
        self.label_38.setObjectName("label_38")
        self.gridLayout_8.addWidget(self.label_38, 1, 0, 1, 1)
        self.subjecturlrule = QtGui.QPlainTextEdit(self.groupBox_9)
        self.subjecturlrule.setObjectName("subjecturlrule")
        self.gridLayout_8.addWidget(self.subjecturlrule, 1, 1, 1, 1)
        self.label_39 = QtGui.QLabel(self.groupBox_9)
        self.label_39.setTextFormat(QtCore.Qt.RichText)
        self.label_39.setObjectName("label_39")
        self.gridLayout_8.addWidget(self.label_39, 2, 0, 1, 1)
        self.subjecturllinkrule = QtGui.QPlainTextEdit(self.groupBox_9)
        self.subjecturllinkrule.setObjectName("subjecturllinkrule")
        self.gridLayout_8.addWidget(self.subjecturllinkrule, 2, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.groupBox_9)
        self.label_40.setTextFormat(QtCore.Qt.RichText)
        self.label_40.setObjectName("label_40")
        self.gridLayout_8.addWidget(self.label_40, 3, 0, 1, 1)
        self.subjectrule = QtGui.QPlainTextEdit(self.groupBox_9)
        self.subjectrule.setObjectName("subjectrule")
        self.gridLayout_8.addWidget(self.subjectrule, 3, 1, 1, 1)
        self.label_41 = QtGui.QLabel(self.groupBox_9)
        self.label_41.setTextFormat(QtCore.Qt.RichText)
        self.label_41.setObjectName("label_41")
        self.gridLayout_8.addWidget(self.label_41, 4, 0, 1, 1)
        self.messagerule = QtGui.QPlainTextEdit(self.groupBox_9)
        self.messagerule.setObjectName("messagerule")
        self.gridLayout_8.addWidget(self.messagerule, 4, 1, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.reverseorder = QtGui.QCheckBox(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reverseorder.sizePolicy().hasHeightForWidth())
        self.reverseorder.setSizePolicy(sizePolicy)
        self.reverseorder.setObjectName("reverseorder")
        self.gridLayout_9.addWidget(self.reverseorder, 0, 0, 1, 1)
        self.onlylinks = QtGui.QCheckBox(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.onlylinks.sizePolicy().hasHeightForWidth())
        self.onlylinks.setSizePolicy(sizePolicy)
        self.onlylinks.setObjectName("onlylinks")
        self.gridLayout_9.addWidget(self.onlylinks, 0, 1, 1, 1)
        self.downloadmode = QtGui.QCheckBox(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadmode.sizePolicy().hasHeightForWidth())
        self.downloadmode.setSizePolicy(sizePolicy)
        self.downloadmode.setObjectName("downloadmode")
        self.gridLayout_9.addWidget(self.downloadmode, 0, 2, 1, 1)
        self.extension = QtGui.QLineEdit(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extension.sizePolicy().hasHeightForWidth())
        self.extension.setSizePolicy(sizePolicy)
        self.extension.setMinimumSize(QtCore.QSize(0, 0))
        self.extension.setMaximumSize(QtCore.QSize(45, 16777215))
        self.extension.setText("")
        self.extension.setMaxLength(10)
        self.extension.setObjectName("extension")
        self.gridLayout_9.addWidget(self.extension, 0, 3, 1, 1)
        self.label_42 = QtGui.QLabel(self.groupBox_9)
        self.label_42.setStyleSheet("color: rgb(172, 202, 239);")
        self.label_42.setObjectName("label_42")
        self.gridLayout_9.addWidget(self.label_42, 0, 4, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_9, 5, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.groupBox_9)
        self.label_43.setObjectName("label_43")
        self.gridLayout_8.addWidget(self.label_43, 5, 0, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayout_8)
        self.verticalLayout_8.addWidget(self.groupBox_9)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_3.setMargin(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_10 = QtGui.QGroupBox(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setStyleSheet("None")
        self.groupBox_10.setFlat(True)
        self.groupBox_10.setCheckable(False)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_10.setContentsMargins(9, 3, 6, 3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.importSQL = QtGui.QPlainTextEdit(self.groupBox_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importSQL.sizePolicy().hasHeightForWidth())
        self.importSQL.setSizePolicy(sizePolicy)
        self.importSQL.setObjectName("importSQL")
        self.horizontalLayout_10.addWidget(self.importSQL)
        self.verticalLayout_3.addWidget(self.groupBox_10)
        self.label_44 = QtGui.QLabel(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setCursor(QtCore.Qt.ArrowCursor)
        self.label_44.setTextFormat(QtCore.Qt.RichText)
        self.label_44.setWordWrap(True)
        self.label_44.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_3.addWidget(self.label_44)
        self.tabWidget.addTab(self.tab_6, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.pushButton = QtGui.QPushButton(RobotDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_11.addWidget(self.pushButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_11)

        self.retranslateUi(RobotDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RobotDialog)

    def retranslateUi(self, RobotDialog):
        RobotDialog.setWindowTitle(QtGui.QApplication.translate("RobotDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("RobotDialog", "基础设置>>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("RobotDialog", "采集器名称", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("RobotDialog", "延迟（秒）", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("RobotDialog", "最大线程数", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("RobotDialog", "列表页设置>>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("RobotDialog", "自动增长", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("RobotDialog", "地址:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("RobotDialog", "参数：[page]、[stock]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("RobotDialog", "手工输入", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("RobotDialog", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("RobotDialog", "到:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("RobotDialog", "通配符长度:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("RobotDialog", "说明: 长度不足时，前面补0.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("RobotDialog", "从:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("RobotDialog", "Stock", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("RobotDialog", "数据源:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("RobotDialog", "基本信息", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("RobotDialog", "采集设置>>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("RobotDialog", "采集页面编码", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("RobotDialog", "列表区域识别规则<br/><font color=\'#ACCAEF\'>截取的地方加上：<br/>[list]</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("RobotDialog", "文章链接URL识别规则<br/><font color=\'#ACCAEF\'>截取的地方加上：<br/>[url]、[title]</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("RobotDialog", "文章标题识别规则<br/><font color=\'#ACCAEF\'>截取的地方加上：<br/>[title]</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("RobotDialog", "文章内容识别规则<br/><font color=\'#ACCAEF\'>截取的地方加上：<br/>[message]</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.reverseorder.setText(QtGui.QApplication.translate("RobotDialog", "倒序采集", None, QtGui.QApplication.UnicodeUTF8))
        self.onlylinks.setText(QtGui.QApplication.translate("RobotDialog", "不采集内容", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadmode.setText(QtGui.QApplication.translate("RobotDialog", "下载模式", None, QtGui.QApplication.UnicodeUTF8))
        self.extension.setToolTip(QtGui.QApplication.translate("RobotDialog", "文件后缀，仅下载模式有效", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("RobotDialog", "修改文件后缀", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("RobotDialog", "其它设置", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("RobotDialog", "采集规则", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("RobotDialog", "执行SQL语句>>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("RobotDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#accaef;\">注：采集完成后执行设置的SQL语句保存到数据库<br />数据：</span><span style=\" font-style:italic; color:#accaef;\">[taskid], [robotid], [key], [url], [title], [content], [runtime]</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("RobotDialog", "导出设置", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("RobotDialog", "保存", None, QtGui.QApplication.UnicodeUTF8))

